### ISSUE TITLE
Thor dependency broken!

### ISSUE THREAD

**Issue by taigrr** [kciter/vimgolf-finder#1]
```
$ vimgolf-finder help |xclip
Traceback (most recent call last):
        8: from /usr/bin/vimgolf-finder:23:in `<main>'
        7: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
        6: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
        5: from /usr/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
        4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
        3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
        2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
        1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'thor' (~> 0.19.1) - did find: [thor-0.20.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=~/.gem/ruby/2.5.0:/usr/lib/ruby/gems/2.5.0', execute `gem env` for more information
```

**Comment by kciter** [comment]
Successfully install on gem version 3.1.2.
