### ISSUE TITLE
Web parser fails when trying to parse diff

### ISSUE THREAD

**Issue by LeMikaelF** [kciter/vimgolf-finder#2]
The program crashes on `vimgolf-finder list` after the "Open your web browser?" prompt with this error:

```
/var/lib/gems/2.3.0/gems/vimgolf-finder-0.1.7/lib/vimgolf_finder/parser.rb:33:in `block in get_challenge': undefined method `content' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:238:in `block in each'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:237:in `upto'
	from /var/lib/gems/2.3.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:237:in `each'
	from /var/lib/gems/2.3.0/gems/vimgolf-finder-0.1.7/lib/vimgolf_finder/parser.rb:27:in `get_challenge'
	from /var/lib/gems/2.3.0/gems/vimgolf-finder-0.1.7/lib/vimgolf_finder/cli.rb:118:in `print_challenge'
	from /var/lib/gems/2.3.0/gems/vimgolf-finder-0.1.7/lib/vimgolf_finder/cli.rb:64:in `list'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /var/lib/gems/2.3.0/gems/vimgolf-finder-0.1.7/lib/vimgolf_finder/cli.rb:20:in `start'
	from /var/lib/gems/2.3.0/gems/vimgolf-finder-0.1.7/bin/vimgolf-finder:9:in `<top (required)>'
	from /usr/local/bin/vimgolf-finder:23:in `load'
	from /usr/local/bin/vimgolf-finder:23:in `<main>'
```

It crashes on both my machines:

* Ubuntu Server 18.04
* Ubuntu 16.04

It seems like the error comes from this line:

     challenge.view_diff = dom.at_css('pre.diff').content

And stems from a change in the DOM on `vimgolf.com`.

**Comment by kciter** [comment]
Sorry. I'm too late. It fixed `0.1.8`.
